language: python
python:
  - "3.6"

services:
  - docker
  - postgresql

before_script: pip install docker-compose

script: 
  - docker-compose build
  - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"